// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CAMapGenerator","status":true,"description":"A map generator based on Cellular Automata","parameters":{"Map IDs":"29","Alive Limit":"2","Dead Limit":"1","Number of Iterations":"5","Randomness":"35","Alive Cell Tile ID":"2816","Dead Cell Tile ID":"2096","Second Alive Cell Tile ID":"2912","Border Tile ID":"2096"}}
];
